// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/logservice/logservice.proto
// DO NOT EDIT!

/*
Package logservice is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/logservice/logservice.proto

It has these top-level messages:
	LogAppDef
	LogLine
	LogRequest
	LogResponse
	LogFilter
	GetLogRequest
	LogEntry
	GetLogResponse
	GetHostLogResponse
	GetHostLogRequest
	GetAppsResponse
	CloseLogRequest
*/
package logservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogAppDef struct {
	Appname       string `protobuf:"bytes,2,opt,name=Appname" json:"Appname,omitempty"`
	DISRepository string `protobuf:"bytes,3,opt,name=DISRepository" json:"DISRepository,omitempty"`
	Groupname     string `protobuf:"bytes,4,opt,name=Groupname" json:"Groupname,omitempty"`
	Namespace     string `protobuf:"bytes,5,opt,name=Namespace" json:"Namespace,omitempty"`
	DeploymentID  string `protobuf:"bytes,6,opt,name=DeploymentID" json:"DeploymentID,omitempty"`
	StartupID     string `protobuf:"bytes,7,opt,name=StartupID" json:"StartupID,omitempty"`
	RepoID        uint64 `protobuf:"varint,8,opt,name=RepoID" json:"RepoID,omitempty"`
	BuildID       uint64 `protobuf:"varint,9,opt,name=BuildID" json:"BuildID,omitempty"`
}

func (m *LogAppDef) Reset()                    { *m = LogAppDef{} }
func (m *LogAppDef) String() string            { return proto.CompactTextString(m) }
func (*LogAppDef) ProtoMessage()               {}
func (*LogAppDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogAppDef) GetAppname() string {
	if m != nil {
		return m.Appname
	}
	return ""
}

func (m *LogAppDef) GetDISRepository() string {
	if m != nil {
		return m.DISRepository
	}
	return ""
}

func (m *LogAppDef) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *LogAppDef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *LogAppDef) GetDeploymentID() string {
	if m != nil {
		return m.DeploymentID
	}
	return ""
}

func (m *LogAppDef) GetStartupID() string {
	if m != nil {
		return m.StartupID
	}
	return ""
}

func (m *LogAppDef) GetRepoID() uint64 {
	if m != nil {
		return m.RepoID
	}
	return 0
}

func (m *LogAppDef) GetBuildID() uint64 {
	if m != nil {
		return m.BuildID
	}
	return 0
}

type LogLine struct {
	Time    int64  `protobuf:"varint,1,opt,name=Time" json:"Time,omitempty"`
	Line    string `protobuf:"bytes,2,opt,name=Line" json:"Line,omitempty"`
	Level   int32  `protobuf:"varint,3,opt,name=Level" json:"Level,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=Status" json:"Status,omitempty"`
	BinLine []byte `protobuf:"bytes,5,opt,name=BinLine,proto3" json:"BinLine,omitempty"`
}

func (m *LogLine) Reset()                    { *m = LogLine{} }
func (m *LogLine) String() string            { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()               {}
func (*LogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogLine) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *LogLine) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogLine) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LogLine) GetBinLine() []byte {
	if m != nil {
		return m.BinLine
	}
	return nil
}

type LogRequest struct {
	AppDef *LogAppDef `protobuf:"bytes,1,opt,name=AppDef" json:"AppDef,omitempty"`
	Lines  []*LogLine `protobuf:"bytes,2,rep,name=Lines" json:"Lines,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogRequest) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *LogRequest) GetLines() []*LogLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

type LogResponse struct {
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type LogFilter struct {
	Host       string     `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	UserName   string     `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	AppDef     *LogAppDef `protobuf:"bytes,3,opt,name=AppDef" json:"AppDef,omitempty"`
	FuzzyMatch string     `protobuf:"bytes,4,opt,name=FuzzyMatch" json:"FuzzyMatch,omitempty"`
}

func (m *LogFilter) Reset()                    { *m = LogFilter{} }
func (m *LogFilter) String() string            { return proto.CompactTextString(m) }
func (*LogFilter) ProtoMessage()               {}
func (*LogFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogFilter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogFilter) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LogFilter) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *LogFilter) GetFuzzyMatch() string {
	if m != nil {
		return m.FuzzyMatch
	}
	return ""
}

type GetLogRequest struct {
	// logical OR of stuff to retrieve - if null means EVERYTHING
	LogFilter []*LogFilter `protobuf:"bytes,1,rep,name=LogFilter" json:"LogFilter,omitempty"`
	// minimum logid to retrieve (0=all) (negative means last n lines)
	MinimumLogID int64 `protobuf:"varint,2,opt,name=MinimumLogID" json:"MinimumLogID,omitempty"`
}

func (m *GetLogRequest) Reset()                    { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()               {}
func (*GetLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLogRequest) GetLogFilter() []*LogFilter {
	if m != nil {
		return m.LogFilter
	}
	return nil
}

func (m *GetLogRequest) GetMinimumLogID() int64 {
	if m != nil {
		return m.MinimumLogID
	}
	return 0
}

type LogEntry struct {
	ID       uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host     string     `protobuf:"bytes,2,opt,name=Host" json:"Host,omitempty"`
	UserName string     `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	Occured  uint64     `protobuf:"varint,4,opt,name=Occured" json:"Occured,omitempty"`
	AppDef   *LogAppDef `protobuf:"bytes,5,opt,name=AppDef" json:"AppDef,omitempty"`
	Line     string     `protobuf:"bytes,6,opt,name=Line" json:"Line,omitempty"`
	Status   string     `protobuf:"bytes,7,opt,name=Status" json:"Status,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogEntry) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *LogEntry) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogEntry) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LogEntry) GetOccured() uint64 {
	if m != nil {
		return m.Occured
	}
	return 0
}

func (m *LogEntry) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *LogEntry) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *LogEntry) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetLogResponse struct {
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *GetLogResponse) Reset()                    { *m = GetLogResponse{} }
func (m *GetLogResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogResponse) ProtoMessage()               {}
func (*GetLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetLogResponse) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetHostLogResponse struct {
	// grouped by host
	Entries []*GetLogResponse `protobuf:"bytes,1,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *GetHostLogResponse) Reset()                    { *m = GetHostLogResponse{} }
func (m *GetHostLogResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHostLogResponse) ProtoMessage()               {}
func (*GetHostLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetHostLogResponse) GetEntries() []*GetLogResponse {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetHostLogRequest struct {
	// logical OR of stuff to retrieve - if null means EVERYTHING
	LogFilter []*LogFilter `protobuf:"bytes,1,rep,name=LogFilter" json:"LogFilter,omitempty"`
	// minimum logid to retrieve (0=all) (negative means last n lines)
	MinimumLogID int64 `protobuf:"varint,2,opt,name=MinimumLogID" json:"MinimumLogID,omitempty"`
}

func (m *GetHostLogRequest) Reset()                    { *m = GetHostLogRequest{} }
func (m *GetHostLogRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHostLogRequest) ProtoMessage()               {}
func (*GetHostLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetHostLogRequest) GetLogFilter() []*LogFilter {
	if m != nil {
		return m.LogFilter
	}
	return nil
}

func (m *GetHostLogRequest) GetMinimumLogID() int64 {
	if m != nil {
		return m.MinimumLogID
	}
	return 0
}

type GetAppsResponse struct {
	AppDef []*LogAppDef `protobuf:"bytes,1,rep,name=AppDef" json:"AppDef,omitempty"`
}

func (m *GetAppsResponse) Reset()                    { *m = GetAppsResponse{} }
func (m *GetAppsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAppsResponse) ProtoMessage()               {}
func (*GetAppsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetAppsResponse) GetAppDef() []*LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

type CloseLogRequest struct {
	AppDef   *LogAppDef `protobuf:"bytes,1,opt,name=AppDef" json:"AppDef,omitempty"`
	ExitCode int32      `protobuf:"varint,2,opt,name=ExitCode" json:"ExitCode,omitempty"`
}

func (m *CloseLogRequest) Reset()                    { *m = CloseLogRequest{} }
func (m *CloseLogRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseLogRequest) ProtoMessage()               {}
func (*CloseLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CloseLogRequest) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *CloseLogRequest) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func init() {
	proto.RegisterType((*LogAppDef)(nil), "logservice.LogAppDef")
	proto.RegisterType((*LogLine)(nil), "logservice.LogLine")
	proto.RegisterType((*LogRequest)(nil), "logservice.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "logservice.LogResponse")
	proto.RegisterType((*LogFilter)(nil), "logservice.LogFilter")
	proto.RegisterType((*GetLogRequest)(nil), "logservice.GetLogRequest")
	proto.RegisterType((*LogEntry)(nil), "logservice.LogEntry")
	proto.RegisterType((*GetLogResponse)(nil), "logservice.GetLogResponse")
	proto.RegisterType((*GetHostLogResponse)(nil), "logservice.GetHostLogResponse")
	proto.RegisterType((*GetHostLogRequest)(nil), "logservice.GetHostLogRequest")
	proto.RegisterType((*GetAppsResponse)(nil), "logservice.GetAppsResponse")
	proto.RegisterType((*CloseLogRequest)(nil), "logservice.CloseLogRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogService service

type LogServiceClient interface {
	LogCommandStdout(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	GetLogCommandStdout(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error)
	GetApps(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*GetAppsResponse, error)
	CloseLog(ctx context.Context, in *CloseLogRequest, opts ...grpc.CallOption) (*common.Void, error)
	// the entries for an application
	GetAppLastEntries(ctx context.Context, in *GetHostLogRequest, opts ...grpc.CallOption) (*GetHostLogResponse, error)
}

type logServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogServiceClient(cc *grpc.ClientConn) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) LogCommandStdout(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/LogCommandStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogCommandStdout(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error) {
	out := new(GetLogResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/GetLogCommandStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetApps(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*GetAppsResponse, error) {
	out := new(GetAppsResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/GetApps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) CloseLog(ctx context.Context, in *CloseLogRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/logservice.LogService/CloseLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetAppLastEntries(ctx context.Context, in *GetHostLogRequest, opts ...grpc.CallOption) (*GetHostLogResponse, error) {
	out := new(GetHostLogResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/GetAppLastEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogService service

type LogServiceServer interface {
	LogCommandStdout(context.Context, *LogRequest) (*LogResponse, error)
	GetLogCommandStdout(context.Context, *GetLogRequest) (*GetLogResponse, error)
	GetApps(context.Context, *common.Void) (*GetAppsResponse, error)
	CloseLog(context.Context, *CloseLogRequest) (*common.Void, error)
	// the entries for an application
	GetAppLastEntries(context.Context, *GetHostLogRequest) (*GetHostLogResponse, error)
}

func RegisterLogServiceServer(s *grpc.Server, srv LogServiceServer) {
	s.RegisterService(&_LogService_serviceDesc, srv)
}

func _LogService_LogCommandStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).LogCommandStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/LogCommandStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).LogCommandStdout(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogCommandStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogCommandStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/GetLogCommandStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogCommandStdout(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/GetApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetApps(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_CloseLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).CloseLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/CloseLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).CloseLog(ctx, req.(*CloseLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetAppLastEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetAppLastEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/GetAppLastEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetAppLastEntries(ctx, req.(*GetHostLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logservice.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogCommandStdout",
			Handler:    _LogService_LogCommandStdout_Handler,
		},
		{
			MethodName: "GetLogCommandStdout",
			Handler:    _LogService_GetLogCommandStdout_Handler,
		},
		{
			MethodName: "GetApps",
			Handler:    _LogService_GetApps_Handler,
		},
		{
			MethodName: "CloseLog",
			Handler:    _LogService_CloseLog_Handler,
		},
		{
			MethodName: "GetAppLastEntries",
			Handler:    _LogService_GetAppLastEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.conradwood.net/apis/logservice/logservice.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/logservice/logservice.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x55, 0xfe, 0x93, 0xdb, 0xb4, 0xfd, 0xbe, 0x69, 0x29, 0xc6, 0x40, 0x15, 0x59, 0x20, 0xc2,
	0x82, 0x54, 0x6a, 0x61, 0x89, 0xd4, 0x34, 0x6e, 0x83, 0x91, 0x5b, 0xa4, 0x09, 0xb0, 0x62, 0x63,
	0xe2, 0xa9, 0x6b, 0xc9, 0xf6, 0x18, 0xcf, 0xb8, 0x90, 0x3e, 0x02, 0x2f, 0xc5, 0xab, 0xf0, 0x1e,
	0x6c, 0x90, 0x67, 0xec, 0x64, 0x6c, 0x68, 0xa9, 0x90, 0x58, 0xd9, 0xf7, 0x67, 0xce, 0xbd, 0xe7,
	0xdc, 0x3b, 0x1a, 0x78, 0x19, 0x27, 0x94, 0x53, 0xb6, 0xe7, 0xd1, 0xc0, 0x89, 0xbc, 0xd1, 0x9c,
	0x46, 0x89, 0xe3, 0x7e, 0xa6, 0xd4, 0x1d, 0x45, 0x84, 0xef, 0x39, 0xb1, 0xcf, 0xf6, 0x02, 0xea,
	0x31, 0x92, 0x5c, 0xfa, 0x73, 0xa2, 0xfc, 0x8e, 0xc4, 0x39, 0x04, 0x2b, 0x8f, 0x3e, 0xba, 0x01,
	0x63, 0x4e, 0xc3, 0x90, 0x46, 0xf9, 0x47, 0x9e, 0x35, 0x7e, 0xd4, 0xa0, 0x67, 0x53, 0x6f, 0x1c,
	0xc7, 0x26, 0x39, 0x47, 0x1a, 0x74, 0xc6, 0x71, 0x1c, 0x39, 0x21, 0xd1, 0xea, 0x83, 0xda, 0xb0,
	0x87, 0x0b, 0x13, 0x3d, 0x82, 0x75, 0xd3, 0x9a, 0x61, 0x12, 0x53, 0xe6, 0x73, 0x9a, 0x2c, 0xb4,
	0x86, 0x88, 0x97, 0x9d, 0xe8, 0x01, 0xf4, 0xa6, 0x09, 0x4d, 0x25, 0x42, 0x53, 0x64, 0xac, 0x1c,
	0x59, 0xf4, 0xcc, 0x09, 0x09, 0x8b, 0x9d, 0x39, 0xd1, 0x5a, 0x32, 0xba, 0x74, 0x20, 0x03, 0xfa,
	0x26, 0x89, 0x03, 0xba, 0x08, 0x49, 0xc4, 0x2d, 0x53, 0x6b, 0x8b, 0x84, 0x92, 0x2f, 0x43, 0x98,
	0x71, 0x27, 0xe1, 0x69, 0x6c, 0x99, 0x5a, 0x47, 0x22, 0x2c, 0x1d, 0x68, 0x07, 0xda, 0x59, 0x2f,
	0x96, 0xa9, 0x75, 0x07, 0xb5, 0x61, 0x13, 0xe7, 0x56, 0xc6, 0xea, 0x28, 0xf5, 0x03, 0xd7, 0x32,
	0xb5, 0x9e, 0x08, 0x14, 0xa6, 0xb1, 0x80, 0x8e, 0x4d, 0x3d, 0xdb, 0x8f, 0x08, 0x42, 0xd0, 0x7c,
	0xeb, 0x87, 0x44, 0xab, 0x0d, 0x6a, 0xc3, 0x06, 0x16, 0xff, 0x99, 0x2f, 0x8b, 0xe5, 0x5a, 0x88,
	0x7f, 0xb4, 0x0d, 0x2d, 0x9b, 0x5c, 0x92, 0x40, 0x08, 0xd0, 0xc2, 0xd2, 0xc8, 0x4a, 0xcf, 0xb8,
	0xc3, 0x53, 0x96, 0xb3, 0xce, 0x2d, 0x51, 0xda, 0x8f, 0x04, 0x48, 0x46, 0xb8, 0x8f, 0x0b, 0xd3,
	0x38, 0x07, 0xb0, 0xa9, 0x87, 0xc9, 0xa7, 0x94, 0x30, 0x8e, 0x9e, 0x41, 0x5b, 0x8e, 0x40, 0xd4,
	0x5f, 0xdb, 0xbf, 0x33, 0x52, 0xa6, 0xbc, 0x9c, 0x0f, 0xce, 0x93, 0xd0, 0x53, 0x68, 0x65, 0x20,
	0x4c, 0xab, 0x0f, 0x1a, 0xc3, 0xb5, 0xfd, 0xad, 0x4a, 0x76, 0x16, 0xc3, 0x32, 0xc3, 0x58, 0x87,
	0x35, 0x51, 0x87, 0xc5, 0x34, 0x62, 0xc4, 0xf8, 0x2a, 0xe7, 0x7d, 0xe2, 0x07, 0x9c, 0x24, 0x19,
	0xc1, 0x57, 0x94, 0x71, 0x51, 0xb4, 0x87, 0xc5, 0x3f, 0xd2, 0xa1, 0xfb, 0x8e, 0x91, 0xe4, 0x6c,
	0xb5, 0x04, 0x4b, 0x5b, 0x69, 0xb3, 0x71, 0x9b, 0x36, 0x77, 0x01, 0x4e, 0xd2, 0xab, 0xab, 0xc5,
	0xa9, 0xc3, 0xe7, 0x17, 0xb9, 0x32, 0x8a, 0xc7, 0xb8, 0x80, 0xf5, 0x29, 0xe1, 0x8a, 0x0c, 0x07,
	0x4a, 0x73, 0x5a, 0x4d, 0x70, 0xab, 0x96, 0x90, 0x41, 0xac, 0x90, 0x30, 0xa0, 0x7f, 0xea, 0x47,
	0x7e, 0x98, 0x86, 0x36, 0xf5, 0x2c, 0x53, 0x34, 0xdd, 0xc0, 0x25, 0x9f, 0xf1, 0xad, 0x06, 0x5d,
	0x9b, 0x7a, 0xc7, 0x11, 0x4f, 0x16, 0x68, 0x03, 0xea, 0x96, 0x29, 0x38, 0x37, 0x71, 0xdd, 0x32,
	0x97, 0x2a, 0xd4, 0xaf, 0x51, 0xa1, 0x51, 0x51, 0x41, 0x83, 0xce, 0x9b, 0xf9, 0x3c, 0x4d, 0x88,
	0x2b, 0x38, 0x35, 0x71, 0x61, 0x2a, 0xfa, 0xb4, 0x6e, 0xa3, 0x4f, 0xb1, 0x5f, 0x6d, 0x65, 0xbf,
	0x56, 0x9b, 0xd4, 0x51, 0x37, 0xc9, 0x38, 0x84, 0x8d, 0x42, 0x2b, 0x39, 0x4a, 0x34, 0x82, 0x4e,
	0xc6, 0xc7, 0x27, 0x2c, 0x97, 0x6a, 0xbb, 0x52, 0x4d, 0xb0, 0xc5, 0x45, 0x92, 0xf1, 0x1a, 0xd0,
	0x94, 0xf0, 0x8c, 0x9d, 0x8a, 0xf2, 0xbc, 0x8a, 0xa2, 0xab, 0x28, 0xe5, 0x92, 0x2b, 0xac, 0x00,
	0xfe, 0x57, 0xb1, 0xfe, 0xf1, 0xf4, 0x0e, 0x61, 0x73, 0x4a, 0xf8, 0x38, 0x8e, 0xd9, 0xb2, 0x6d,
	0xf5, 0xc2, 0x34, 0xfe, 0xa8, 0xb4, 0xf1, 0x01, 0x36, 0x27, 0x01, 0x65, 0xe4, 0xef, 0xaf, 0x9c,
	0x0e, 0xdd, 0xe3, 0x2f, 0x3e, 0x9f, 0x50, 0x57, 0x5e, 0x8b, 0x16, 0x5e, 0xda, 0xfb, 0xdf, 0xeb,
	0xe2, 0x32, 0xcf, 0xe4, 0x61, 0x34, 0x81, 0xff, 0x6c, 0xea, 0x4d, 0x68, 0x18, 0x3a, 0x91, 0x3b,
	0xe3, 0x2e, 0x4d, 0x39, 0xda, 0xa9, 0xa0, 0xe7, 0x5d, 0xe8, 0x77, 0x7f, 0xf1, 0xe7, 0x04, 0x6d,
	0xd8, 0x92, 0xe2, 0x97, 0x71, 0xee, 0xfd, 0x6e, 0x3a, 0x12, 0xea, 0x86, 0xc1, 0x65, 0x53, 0xce,
	0x15, 0x44, 0xfd, 0x51, 0xfe, 0x00, 0xbc, 0xa7, 0xbe, 0xab, 0xdf, 0xaf, 0x1c, 0x2a, 0x89, 0xfc,
	0x02, 0xba, 0x85, 0x6a, 0xa8, 0x94, 0x58, 0xd1, 0x52, 0x2f, 0x61, 0x22, 0x2c, 0x96, 0x63, 0x1c,
	0xc7, 0xb6, 0xc3, 0x78, 0xbe, 0x31, 0xe8, 0x61, 0xa5, 0x50, 0x79, 0x77, 0xf4, 0xdd, 0xeb, 0xc2,
	0xb2, 0x95, 0xa3, 0x27, 0xf0, 0x38, 0x22, 0x5c, 0x7d, 0xd6, 0xf2, 0x87, 0x2e, 0x7b, 0xd9, 0x94,
	0xb3, 0x1f, 0xdb, 0xe2, 0x5d, 0x3b, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0x08, 0x9c, 0x03, 0x50,
	0x54, 0x07, 0x00, 0x00,
}
